In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5))

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


In [8]:
x2[0,0] = 12

In [9]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [3]:
x1

array([9, 4, 0, 3, 8, 6])

In [5]:
print(x1[:3],
x1[3:],
x1[1:4],
x1[::2],
x1[1::2])

[9 4 0] [3 8 6] [4 0 3] [9 0 8] [4 3 6]


In [6]:
x1[::-1]

array([6, 8, 3, 0, 4, 9])

In [7]:
x1[4::-2]

array([8, 0, 9])

In [10]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [11]:
x2[:2,:3]

array([[12,  1,  3],
       [ 4,  0,  2]])

In [13]:
x2[:3, ::2]

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [14]:
x2[::-1, ::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [16]:
x2[:,0]

array([12,  4,  0])

In [17]:
x2[0,:]

array([12,  1,  3,  7])

In [18]:
x2[0]

array([12,  1,  3,  7])

In [19]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [21]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  1]
 [ 4  0]]


In [23]:
x2_sub[0,0] = 99
print(x2_sub)
print(x2)

[[99  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [26]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [27]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)
print(x2)

[[42  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [28]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
x = np.array([1, 2, 3])
x.reshape((1,3))

array([[1, 2, 3]])

In [30]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [31]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [32]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [33]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [34]:
z = np.array([0, 0, 0])
np.concatenate([x, y, z])

array([1, 2, 3, 3, 2, 1, 0, 0, 0])

In [35]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [36]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [37]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
y = np.array([[99],
              [99]])
np.hstack([grid,y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [42]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [44]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [47]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
